MAX_PLAYER_COUNT = 20

GAME_STATE_GAME   = 0
GAME_STATE_REVEAL = 1
GAME_STATE = [
  GAME_STATE_GAME,
  GAME_STATE_REVEAL,
]

LIVING_STATE_HIDDEN = 0
LIVING_STATE_ALIVE  = 1
LIVING_STATE_DEAD   = 2
LIVING_STATE = [
  LIVING_STATE_HIDDEN,
  LIVING_STATE_ALIVE,
  LIVING_STATE_DEAD,
]

TYPE_STATE_CHARACTER = 0
TYPE_STATE_TRAVELLER = 1
TYPE_STATE = [
  TYPE_STATE_CHARACTER,
  TYPE_STATE_TRAVELLER,
]

TEAM_STATE_HIDDEN = 0
TEAM_STATE_GOOD   = 1
TEAM_STATE_EVIL   = 2
TEAM_STATE = [
  TEAM_STATE_HIDDEN,
  TEAM_STATE_GOOD,
  TEAM_STATE_EVIL,
]

COLOR_WHITE = (  0,   0,   0)
COLOR_BLACK = (255, 255, 255)

PLAYER_COLOR_HIDDEN    = 0
PLAYER_COLOR_CHARACTER = 1
PLAYER_COLOR_TRAVELLER = 2
PLAYER_COLOR_DEAD      = 3
PLAYER_COLOR_GOOD      = 4
PLAYER_COLOR_EVIL      = 5
PLAYER_COLORS = {
  PLAYER_COLOR_HIDDEN:    (255, 255, 255),
  PLAYER_COLOR_CHARACTER: (244, 241, 234),
  PLAYER_COLOR_TRAVELLER: (205, 170,  56),
  PLAYER_COLOR_DEAD:      ( 63,  25,  66),
  PLAYER_COLOR_GOOD:      ( 82, 182, 255),
  PLAYER_COLOR_EVIL:      (255,  54,  54),
}
