MAX_PLAYER_COUNT = 20

GAME_STATE_GAME   = 0
GAME_STATE_REVEAL = 1
GAME_STATE = [
  GAME_STATE_GAME,
  GAME_STATE_REVEAL,
]

LIVING_STATE_HIDDEN = 0
LIVING_STATE_ALIVE  = 1
LIVING_STATE_DEAD   = 2
LIVING_STATE = [
  LIVING_STATE_HIDDEN,
  LIVING_STATE_ALIVE,
  LIVING_STATE_DEAD,
]

TYPE_STATE_PLAYER    = 0
TYPE_STATE_TRAVELLER = 1
TYPE_STATE = [
  TYPE_STATE_PLAYER,
  TYPE_STATE_TRAVELLER,
]

TEAM_STATE_HIDDEN = 0
TEAM_STATE_GOOD   = 1
TEAM_STATE_EVIL   = 2
TEAM_STATE = [
  TEAM_STATE_HIDDEN,
  TEAM_STATE_GOOD,
  TEAM_STATE_EVIL,
]
