MAX_PLAYER_COUNT = 20

ALIVE_STATE_HIDDEN = 0
ALIVE_STATE_ALIVE = 1
ALIVE_STATE_DEAD_VOTE = 2
ALIVE_STATE_DEAD_NO_VOTE = 3
ALIVE_STATE = [
  ALIVE_STATE_HIDDEN,
  ALIVE_STATE_ALIVE,
  ALIVE_STATE_DEAD_VOTE,
  ALIVE_STATE_DEAD_NO_VOTE,
]

TYPE_STATE_PLAYER = 0
TYPE_STATE_TRAVELLER = 1
TYPE_STATE = [
  TYPE_STATE_PLAYER,
  TYPE_STATE_TRAVELLER,
]

class PlayerState:
  nominated_player = -1
  players: list[tuple[int, int]] = [
    (ALIVE_STATE_HIDDEN, TYPE_STATE_PLAYER)
    for _ in range(MAX_PLAYER_COUNT)
  ]
